language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: JRs5AsXb12f/4XQreWvRnFvNeQO+GsbraA4JJiSVbRlbCxmzakS4ia1w4I1A8BEPQxi/rWC89UiKA3sFPLE2pB/94M3B33W9fDSC1iLlWPY7ZkFHyznCZ/zjZ/dg7fLEKp1lm4rG319Wcs4EsnF39yH7zeiOk2ev/HQOC94GORlFN5b7EML3GQom+3EKTMfWuNvuEbykvYfwwbQKEuppgTrQoi/c6nOdQglvryXLxgDLDRhkYFPEFnsbcr4GYpdEERzj69GCnS4ky+LjtWC6D8ey6V5PUyJ5NUVzf2+h32tpUcZlTShRrcF3wRcW4Vdph2whRVff2K0NWT18IzAu7A+ahkkwVeSv8/j7pB7bsI7jb0FzkAXOTM9wx2E1e7yd6RcX188zdllkbC2emB7hLwgwKkVJTab+g3kxSin29plF0zEtGWI8d3EWs4gmgFpskx940G5SkO32T3USilVNlCbimEaPxGD4D53lbZAIRy/sw7i3oEEWXKZMQ7Op+jqPBor+ImMMy83h0ewaoaj1agZLkAg24s/5Lbj1JnYH0QnRjOOz5Qzi/MQ8RNqDFakyMVxITuWVi93isGjZ5Nfud99MdRE3Oh34chM7bdMx/chP+NaNTiCWYUV5Max2H0a5V2tHXnqfF/yHXMrSedxBwMmptYaYD1+5ih/Mrd9qEUg=
  app: aqueous-escarpment-36658
  on:
    repo: djiani/myfavoritemeal_api
