language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: cIAiBt9dYtmemWMMZ54PuDDAg/xYbKglulV6Vh6BLagAkhr/lO+e6yyt3WiRnGx3oLgD8RvJrRAeYql5EKdfqgOuvkM+2xTGzsMBQDKyV36EwyKqnQm0Fp1skA+rTuEeWehoRgQZraFO12mPbsbTmO6qXi63g/dUIpXNmQYLKI4BGRFtkuxWbr5sE9wjlY63V5Rd+7bC38jyiqiK6MTJy7HhE1IIkOHlCfBb465Ny1hclEtD0nHv1onta1Aih9cH4VebheutlU0rH5ERTVTudG/AZmX8RsKy937PWnam4E0LPBfb3tucvbaAUhy8O3YTYxbx+WoI0BzJuhjl+ZcVebSCv+RwEXm6XlzJvXFJqnquu1wtOG5MBe3Ub+XnI9NMvHvNK/+qr5257/9ape67QGvNM24J+lBiR6102XdJxi/2tPjm9PSoRrSH8vVKQrQAJ2vkKfupQO9xzNdF6wpw5wRsQcYb1+kHMCM+Os9/QiZScbIETlNEfLWoyKtSrgMwM8el6iF5K1Yu4P52nOwHvYiGbHY2SgiANSpLmniWRzt2nhByFt7BtRInk7KwgiXgDkjy+u1rh+Gsf3QX2VPlkGevnHuuuDXuPZvRH/0T+O3linkljeG7w6038gRUaATVLFa9vl/dHq5l6t3PEp9iOHmzgrILAJr24YfGbGcin/s=
  app: aqueous-escarpment-36658
  on:
    repo: djiani/myfavoritemeal_api
