language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: IbX3Inu855dY4Ff/6YG5Zo9ZRfAlyMsgilR7GOU9aJ90/1PdknIN0Q/tqo1kPDW6pr6vAsrgn3sAh9wonAAsGH3txO2nXeYg40qzqeUqoI7jXIaXagQPfxpYqJTchIhggGpMHyFudog6V+5+S+bw+edRQTav9Z1/N5tmibIARMMAwrcuQ0Dgs35cqf3w5dzZ+DX/UZGHWtYHmdJY3hgYHR0gmOX011O/JA50T1KS9eIHu2X7Ybsbh0LLIvVHkmWfNfg7XrHqCgTJJTBPffA3r5YsOUjqDfKyp0Bp2teowcoE6pbO1FtyLLIoVZXHSZFD8Z4EA0EVRzbABUdSx1e+r+apFKTV2xtfk67pbnIS0dnRdLZ7oc+KkNDKi9Gg0ZiAfb4ert3BngkwqwjJqNIJQeQ2Jd7jGVfWmakOAwTIqaotPjnpFiob4YSHV+kNU5CKLMGewCTJGjpo8meSy1jcUAcOxy2KpdAO5JDTZ4trCGMeLCXkyYvi0VKUHqiqdpX94M9YC1rroVx8T7PgAdRQVxRGYM58HA16Gbo4hxFSUmhPgcTE5zYhA/WaxbjA0AOaBV3WsjeFmHxKR7K35RqodC2HG/e1fnW/M32mjwq7/vySpK042PV6d+9qCwzQ/pYmFiSbrFSS8VrQMODTH6hh1rMlcAsXnnZudFOIzI8ZxtA=
  app: aqueous-escarpment-36658
  on:
    repo: djiani/myfavoritemeal_api
