language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: PBPAULnNNfT1qxUGeH3CGhOy2Me1cq4VwkETCclgXlDW8ZrP1t6/e/ExagwWA1xZdHE9uYjTWGWIVfLx5EuQkW+RM5Og3PiADSlYUlEztmJcdyx3c97hR6HnvaeIIUWqgLxiDNJv8+s8gviAln13UVp3RFhU+U3OmwHup20IEQQBRVrFaqcd40pbJPRuZyJfmrdvQEapMlN4C/pqxzjavgd4xevLPaMaEJAPTqc75RDhAjI8+icjw0KK1hO+Xkxpq62m29X3UzfKc4xMp/KT5J6CteQWf/c3RjRGim5/yGN+pqPBaLziHTP60FrNWh96orrkIdvYFGEiBTJy8auxwnHQQDgR70JkTw2no2URyx/v4A7RBh9ll1QBw+ih6H6cZq9LiCVjqTLaIV+dWho714U0YHYccoj7TgcgY5b6RJ/DOVdWW9QXOVah2eMSX/8yTBMwjUzx2uXZ6akHZNek4y5Ve/RpCY6xviGUkIUb5PJmPT341pNk72w5VIl7MV9lZQtioWIUAfoR9b1aJoj5MYbIirQFLKol3YGUKsaC6BUhgxVsDWOpIA3pL5z52rkq8+LV4rhd+3Oc5c2RCCxUnOEoQLP8J7IaoOUmKWQU+SwsLCTL4khpvcoH/hCZ4ZUoL/M22qyMxOPa3PDOTJKftd1/lBVM/w18B3/kApsN5GQ=
  app: aqueous-escarpment-36658
  on:
    repo: djiani/myfavoritemeal_api
